name: ebroker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+23

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  any_link_preview: ^3.0.0
  audioplayers: ^3.0.1
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^2.3.7
  country_code_picker: ^2.0.2
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  encrypt: ^5.0.3
  file_icon: ^1.0.0
  file_picker: ^5.2.4
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_core_platform_interface: 4.5.3
  firebase_dynamic_links: ^5.0.17
  firebase_messaging: ^14.3.0
  flick_video_player: ^0.5.0
  flutter_bloc: ^8.1.1
  flutter_html: ^3.0.0-beta.1
  flutter_native_image: 0.0.6+1
  flutter_paypal: ^0.0.8
  flutter_paystack: ^1.0.7
  flutter_sim_country_code: ^0.1.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_stripe: ^9.4.0
  flutter_svg: 1.1.6
  flutter_typeahead: ^4.3.7
  flutter_vibrate: ^1.3.0
  fluttertoast: ^8.2.1
  geocoding: ^2.1.0
  google_maps_flutter: 2.2.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.3
  http_parser: any
  hydrated_bloc: ^9.1.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  label_marker: ^1.0.1
  latlong2: ^0.9.0
  launch_review: ^3.0.1
  logger: ^1.4.0
  lottie: ^2.1.0
  mason_cli: ^0.1.0-dev.49
  mime: any
  mime_type: ^1.0.0
  octo_image: ^1.0.2
  open_filex: ^4.3.2
  package_info_plus: ^4.0.2
  palette_generator: ^0.3.3+2
  panorama: ^0.4.1
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  razorpay_flutter: ^1.3.5
  record: ^4.4.4
  rive: ^0.9.1
  share_plus: ^4.4.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sms_autofill: ^2.2.0
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.1.6
  video_player: ^2.4.10
  youtube_player_flutter: ^8.1.2

dependency_overrides:
  flutter_svg: ^1.0.0
  intl: ^0.17.0
  wakelock: ^0.6.2
  package_info_plus: ^4.0.2
  wakelock_windows: any
  win32: null
  # file_version_info: any

dev_dependencies:

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  rename: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - assets/image/
    - assets/svg/
    - assets/languages/
    - assets/lottie/
    - assets/riveAnimations/
    - assets/chat_background/
    - assets/chat_background/
    - assets/svg/Logo/
    - assets/city.jpg
    - assets/map.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
