// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR7MBiXYLzQLULUpxdFAK4guUCpIaGNEQ',
    appId: '1:64121383374:web:eb684dc55f9c3f3b1ca39f',
    messagingSenderId: '64121383374',
    projectId: 'e-broker-a60b7',
    authDomain: 'e-broker-a60b7.firebaseapp.com',
    storageBucket: 'e-broker-a60b7.appspot.com',
    measurementId: 'G-21WBCFY35X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUksrZWx0F2rE-J22LPvH1hGo2jCKtAI',
    appId: '1:64121383374:android:867e8fc11582a6711ca39f',
    messagingSenderId: '64121383374',
    projectId: 'e-broker-a60b7',
    storageBucket: 'e-broker-a60b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7FjT-F7kHxEDq8A8bJK8GfRQbbwoNo0',
    appId: '1:64121383374:ios:e4273b23d7c495051ca39f',
    messagingSenderId: '64121383374',
    projectId: 'e-broker-a60b7',
    storageBucket: 'e-broker-a60b7.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );
}
